name: 'Test'
on: [push, pull_request]
env:
  DB_URL: jdbc:postgresql://localhost:5432/postgres
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - run: "./gradlew update bootJar test --no-daemon --no-build-cache"